#!/usr/bin/env bash
# Optional: patch std_msgs from a colcon install when using typed message crates.
# Native Spanda rclrs uses dynamic messages and does not require this file.
set -euo pipefail

INSTALL_PREFIX="${1:-}"

search_paths() {
  if [[ -n "$INSTALL_PREFIX" ]]; then
    echo "$INSTALL_PREFIX"
  fi
  if [[ -n "${AMENT_PREFIX_PATH:-}" ]]; then
    echo "$AMENT_PREFIX_PATH" | tr ':' '\n'
  fi
}

found=0
while IFS= read -r prefix; do
  [[ -z "$prefix" ]] && continue
  rust_dir="$prefix/share/std_msgs/rust"
  if [[ -f "$rust_dir/Cargo.toml" ]]; then
    found=1
    echo "std_msgs Rust bindings available at $rust_dir"
    break
  fi
done < <(search_paths)

if [[ "$found" -eq 0 ]]; then
  echo "No std_msgs Rust bindings found (not required for spanda-ros2-rclrs-native)" >&2
  exit 0
fi

mkdir -p .cargo
config=".cargo/config.toml"
{
  echo "# Generated by scripts/setup-ros2-rust-cargo.sh — do not edit by hand"
  echo "[patch.crates-io]"
  echo "std_msgs = { path = \"$rust_dir\" }"
} >"$config"
echo "Wrote $config"
